import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useGenres } from "../hooks/albums/useGenres";
import { GenreDto } from "./dtos";

const Home: NextPage = () => {
    axios.defaults.baseURL = "https://localhost:7272/api";
    const { data: genres, isLoading } = useGenres();
    if (isLoading) {
        return <div>Loading...</div>;
    }
    return (
        <div>
            <Head>
                <title>MetalStorm client</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                style={{
                    display: "grid",
                    gridAutoFlow: "column",
                    gridTemplateRows: "repeat(50, 1fr)",
                }}
            >
                {genres
                    .sort(
                        (a: GenreDto, b: GenreDto) => b.bandCount - a.bandCount
                    )
                    .map((genre: GenreDto) => (
                        <span key={genre.id}>
                            <Link
                                href={`/bands?genre=${genre.id}`}
                                key={genre.id}
                            >
                                <a>
                                    {genre.name} ({genre.bandCount})
                                </a>
                            </Link>
                        </span>
                    ))}
            </div>
        </div>
    );
};

export default Home;
