import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

interface Album {
    id: number;
    name: string;
}

const Home: NextPage = () => {
    axios.defaults.baseURL = "https://localhost:7272/api";
    const [albums, setAlbums] = useState([]);
    useEffect(() => {
        axios.get("/Albums").then((resp) => setAlbums(resp.data));
    });

    return (
        <div>
            <Head>
                <title>MetalStorm client</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ul>
                {albums.map((album: Album) => (
                    <li key={album.id}>{album.name}</li>
                ))}
            </ul>
        </div>
    );
};

export default Home;
